// Generated by CoffeeScript 1.7.1
var duration, height, log, path, projection, quantize, rateById, ready, svg, val, width;

log = console.log.bind(console);

width = window.innerWidth;

height = window.innerHeight;

rateById = d3.map();

quantize = d3.scale.quantize().domain([0, .15]).range(d3.range(9).map(function(i) {
  return "q" + i + "-9";
}));

projection = d3.geo.albersUsa().scale(1880).translate([width / 2, height / 2]);

path = d3.geo.path().projection(projection);

svg = d3.select("body").append("svg").attr("width", width).attr("height", height);

val = d3.scale.linear().range([1, 0]);

duration = 1;

ready = function(error, us) {
  var counties;
  counties = topojson.feature(us, us.objects.counties).features;
  val.domain([
    d3.min(counties, function(d) {
      return rateById.get(d.id);
    }), d3.max(counties, function(d) {
      return rateById.get(d.id);
    })
  ]);
  svg.append("g").attr("class", "counties").selectAll("path").data(counties).enter().append("path").attr("d", path).attr('fill', function(d) {
    return d3.hsl(210, 0.0, 0.26);
  }).transition().delay(function(d, i) {
    return i * duration;
  }).attr('fill', function(d) {
    var s;
    s = Math.random() * 0.5 + 0.5;
    return d3.hsl(0, 0.0, s);
  }).duration(function(d) {
    return 750;
  }).transition().delay(function(d, i) {
    return i * duration * 2;
  }).attr('fill', function(d) {
    var s;
    s = val(rateById.get(d.id));
    return d3.hsl(215 + Math.round(Math.random() * 10) - 5, s, s);
  }).duration(function(d) {
    return Math.random() * 750 + 750;
  });
  return svg.append("path").datum(topojson.mesh(us, us.objects.states, function(a, b) {
    return a !== b;
  })).attr("class", "states").attr("d", path);
};

queue().defer(d3.json, "us.json").defer(d3.tsv, "unemployment.tsv", function(d) {
  return rateById.set(d.id, +d.rate);
}).await(ready);

d3.select(self.frameElement).style("height", height + "px");

/*
//@ sourceMappingURL=main.map
*/
